#!/bin/bash

GRADECOPE_SWITCHBOARD_USER="gradecope"
GRADECOPE_RUNNER_USER="gradecope-runner"

GRADECOPE_STUDENTS_GROUP="gradecope-students"

GRADECOPE_RUNNER_PORT=10080
GRADECOPE_SOCKETS_DIR="gradecope-sockets"

GRADECOPE_DATABASE="gradecope"

export \
  GRADECOPE_SWITCHBOARD_USER GRADECOPE_RUNNER_USER \
  GRADECOPE_STUDENTS_GROUP \
  GRADECOPE_RUNNER_PORT GRADECOPE_SOCKETS_DIR \
  GRADECOPE_DATABASE